apiVersion: apps/v1
kind: Deployment
metadata:
  name: chainops-be
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: chainops-be
  template:
    metadata:
      labels:
        app: chainops-be
    spec:
      containers:
        - name: api
          image: {{ .Values.api.image }}
          ports:
            - containerPort: 8080
